@host = http://localhost:3000 

GET {{host}}/usuarios

###

GET {{host}}/usuarios/Ryu

###

POST {{host}}/usuarios
Content-Type: application/json

{
    "id": 6,
    "nombre": "Zangier",
    "edad": "45",
    "lugarProcedencia": "Turquia"
}

###

PUT {{host}}/usuarios/Ryu
Content-Type: application/json

{
    "nombre": "Vega",
    "edad": "34",
    "lugarProcedencia": "España"
}






